const books = [
    {
        id: 1,
        title: "Atomic Habits",
        author: "James Clear",
        year: 2018,
        description: "Panduan praktis untuk membentuk kebiasaan kecil yang menghasilkan perubahan besar dalam hidup.",
        image: "https://ebooks.gramedia.com/ebook-covers/49184/image_highres/ID_AHPK2019MTH09AHP.jpg",
    },
    {
        id: 2,
        title: "The Subtle Art of Not Giving a F*ck",
        author: "Mark Manson",
        year: 2016,
        description: "Sebuah pendekatan menyegarkan dalam menghadapi kehidupan, dengan fokus pada hal-hal yang benar-benar penting.",
        image: "https://images-na.ssl-images-amazon.com/images/I/71QKQ9mwV7L.jpg",
    },
    {
        id: 3,
        title: "Rich Dad Poor Dad",
        author: "Robert T. Kiyosaki",
        year: 1997,
        description: "Pelajaran keuangan dari dua sosok ayah, membongkar pola pikir tentang uang dan investasi.",
        image: "https://images-na.ssl-images-amazon.com/images/I/81bsw6fnUiL.jpg",
    },
    {
        id: 4,
        title: "Ikigai: The Japanese Secret to a Long and Happy Life",
        author: "Héctor García & Francesc Miralles",
        year: 2016,
        description: "Mengungkap filosofi hidup panjang dan bermakna dari budaya Jepang.",
        image: "https://images-na.ssl-images-amazon.com/images/I/71tbalAHYCL.jpg",
    },
    {
        id: 5,
        title: "Deep Work",
        author: "Cal Newport",
        year: 2016,
        description: "Strategi untuk mencapai fokus mendalam dan produktivitas maksimal di era distraksi digital.",
        image: "https://id-test-11.slatic.net/p/8d680a5d5a2ec725fe5a80d6aba4fa3d.jpg",
    },
    {
        id: 6,
        title: "Start With Why",
        author: "Simon Sinek",
        year: 2009,
        description: "Membongkar pentingnya memulai segala sesuatu dengan 'mengapa' sebagai fondasi utama.",
        image: "https://cdn.gramedia.com/uploads/items/9786020628837_start-with-wh.jpg",
    },
    {
        id: 7,
        title: "The Psychology of Money",
        author: "Morgan Housel",
        year: 2020,
        description: "Pandangan unik tentang cara orang berpikir, merasa, dan bertindak terhadap uang.",
        image: "https://images-na.ssl-images-amazon.com/images/I/61-hMfd7NGL.jpg",
    },
    {
        id: 8,
        title: "Thinking, Fast and Slow",
        author: "Daniel Kahneman",
        year: 2011,
        description: "Penjelasan mendalam tentang dua sistem berpikir manusia dan bagaimana mereka memengaruhi keputusan.",
        image: "https://cdn.gramedia.com/uploads/items/9786020637181_THINKING_FAST_AND_SLOW_C_1_4-1.jpg",
    },
    {
        id: 9,
        title: "Can’t Hurt Me",
        author: "David Goggins",
        year: 2018,
        description: "Kisah inspiratif tentang mengatasi batas diri dan membentuk mentalitas tanpa batas.",
        image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1536184191i/41721428.jpg",
    },
    {
        id: 10,
        title: "The 5 AM Club",
        author: "Robin Sharma",
        year: 2018,
        description: "Rahasia sukses dan produktivitas dari kebiasaan bangun pagi yang luar biasa.",
        image: "https://ebooks.gramedia.com/ebook-covers/45294/image_highres/HCO_T5AMC2018MTH12.jpeg",
    }
];

export default books;
